# Generated by Django 5.1.2 on 2024-11-03 17:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Title')),
                ('txt', ckeditor.fields.RichTextField(default='', verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Welcome Text',
                'verbose_name_plural': 'Welcome Texts',
            },
        ),
    ]
