# Generated by Django 5.1.2 on 2024-11-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_phone_telegram_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='number',
            field=models.CharField(default='+994556449164', max_length=200, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='number',
            field=models.CharField(default='+994556449164', max_length=200, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='number',
            field=models.CharField(default='+994556449164', max_length=200, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
